[package]
name = "toast-terminal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
toast-core = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
parking_lot = { workspace = true }
